# Generated by Django 3.2 on 2023-01-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='users/avatares/default_avatar.jpg', upload_to='users/avatares/')),
                ('phone_number', models.CharField(default='', max_length=9, null=True)),
                ('region', models.CharField(default='', max_length=255, null=True)),
                ('city', models.CharField(default='', max_length=255, null=True)),
                ('province', models.CharField(default='', max_length=255, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('postal_code', models.CharField(default='', max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
