# Generated by Django 3.2 on 2022-12-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='zipcode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='province',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
    ]
