# Generated by Django 3.2 on 2022-12-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20221215_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='', upload_to='users/prueba/'),
        ),
    ]
