# Generated by Django 3.2 on 2022-12-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='users/prueba/Apple_Iphone_14_Pro_Max.png', upload_to='users/prueba/'),
        ),
    ]
